### ISSUE TITLE
Unable to run ./orchest install getting 404 Client Error: Not Found for url: http+docker://localhost/v1.40/networks/orchest

### ISSUE THREAD

**Issue by samos123** [orchest/orchest#103]
I tried out the installation steps but hitting an error when running `./orchest install`. See detailed log below.

versions:
```
docker --version
Docker version 19.03.13, build 4484c46d9d
Orchest commit: 489bde8f2fe217e56e79cd55cb90d493d53006a3 (Jan 4)
```

Detailed logs:
```
Unable to find image 'orchest/orchest-ctl:latest' locally
latest: Pulling from orchest/orchest-ctl                                                            
6ec7b7d162b2: Already exists        
80ff6536d04b: Pull complete                                                                         
6c51d3836e95: Pull complete                         
6ce84404158b: Pull complete                                                                                       
6e001f327b45: Pull complete                                                          
31686f95ea4e: Pull complete                                                                                                         
c6c989f83870: Pull complete                                                         
936cc2d383ad: Pull complete                                                               
Digest: sha256:e22ee169ea6709e29839a865cbd6ffc3f6d5e8390b1f94fb85edc3e920f888c4           
Status: Downloaded newer image for orchest/orchest-ctl:latest                                 
Installation might take some time depending on your network bandwidth. Starting installation...     
Pulling images: 14/14|#############################################################################|
Orchest sends anonymized telemetry to analytics.orchest.io. To disable it, please refer to:      
        https://orchest.readthedocs.io/en/stable/user_guide/other.html#configuration      
                                                                                                                             
Traceback (most recent call last):                                                                  
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()                                                                                   
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status   
    raise HTTPError(http_error_msg, response=self)                                                                                                          
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/networks/orchest
                                                                                                                                                             
During handling of the above exception, another exception occurred:                                                                                          
                                                                                    
Traceback (most recent call last):                                                        
  File "/usr/local/lib/python3.7/site-packages/app/utils.py", line 156, in install_network
    docker_client.networks.get(config.DOCKER_NETWORK)                                         
  File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 182, in get
    self.client.api.inspect_network(network_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 213, in inspect_network
    return self._result(res, json=True)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.40/networks/orchest: Not Found ("network orchest not found")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.40/networks/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/orchest", line 8, in <module>
    sys.exit(__entrypoint())
  File "/usr/local/lib/python3.7/site-packages/app/main.py", line 59, in __entrypoint
    app()
  File "/usr/local/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/app/main.py", line 124, in install
    cmdline.install(lang)
  File "/usr/local/lib/python3.7/site-packages/app/cmdline.py", line 64, in install
    utils.install_network()
  File "/usr/local/lib/python3.7/site-packages/app/utils.py", line 173, in install_network
    config.DOCKER_NETWORK, driver="bridge", ipam=ipam_config
  File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 156, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 153, in create_network
    return self._result(res, json=True)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.40/networks/create: Internal Server Error ("failed to update bridge store for object
type *bridge.networkConfiguration: open /var/lib/docker/network/files/local-kv.db: read-only file system")
ERRO[0224] Error waiting for container: container 01b7da9a8884603afad1b15cd954e52866596226fa27c0eb41ceeedb022bf588: driver "btrfs" failed to remove root file
system: Failed to destroy btrfs snapshot /var/lib/docker/btrfs/subvolumes for 213212e826d1f2079d242a75aa60c79d7bbfe7a3ac1b67e0e641d532f80434b2: read-only file system
```

**Comment by samos123** [comment]
Looks like I ran out of space on my node running docker... closing for now.

**Comment by ricklamers** [comment]
@samos123 pardon the issue! We will try to better inform users of system requirements. We're currently reviewing how to best inform users about it.

**Comment by samos123** [comment]
Nah wasn't Orchests issue at all. I just wasn't aware my system was already very close to running out of space. I'm running on Crostini Debian on a Pixelbook and only got 50GB of space for Linux there. That being said having minimal requirements documented and a check in the bash script might help stupid users like me.
