### ISSUE TITLE
Orchest CLI failure message when no cluster is detected

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#1056]
**Describe the problem this improvement solves**
When using the `orchest-cli` with no running cluster (e.g. minikube has been stopped) the CLI will fail to find the `kube-config` file, will print an error trace and exit. 

**Describe the solution you'd like**
A more elegant error message which explains that the file could not be found and asks, perhaps, if your cluster *is* running.

This is what you would get currently
```bash
Traceback (most recent call last):
  File "/home/jacopo/.local/lib/python3.8/site-packages/orchestcli/cmds.py", line 30, in <module>
    config.load_kube_config()
  File "/home/jacopo/.local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 808, in load_kube_config
    loader = _get_kube_config_loader(
  File "/home/jacopo/.local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 770, in _get_kube_config_loader
    return KubeConfigLoader(
  File "/home/jacopo/.local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 206, in __init__
    self.set_active_context(active_context)
  File "/home/jacopo/.local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 259, in set_active_context
    self._current_context = self._config['contexts'].get_with_name(
  File "/home/jacopo/.local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 657, in get_with_name
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected object with name  in /home/jacopo/.kube/config/contexts list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jacopo/.local/bin/orchest", line 5, in <module>
    from orchestcli.cli import cli
  File "/home/jacopo/.local/lib/python3.8/site-packages/orchestcli/cli.py", line 57, in <module>
    from orchestcli import cmds
  File "/home/jacopo/.local/lib/python3.8/site-packages/orchestcli/cmds.py", line 32, in <module>
    config.load_incluster_config()
  File "/home/jacopo/.local/lib/python3.8/site-packages/kubernetes/config/incluster_config.py", line 118, in load_incluster_config
    InClusterConfigLoader(
  File "/home/jacopo/.local/lib/python3.8/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/home/jacopo/.local/lib/python3.8/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.
```

**Comment by astrojuanlu** [comment]
Wasn't this fixed in https://github.com/orchest/orchest/commit/eac7171d61a80a5a86ca765765e57ce2a8a81a56? (See #1053)

**Comment by yannickperrenet** [comment]
Funny coincidence you both bumping into this issue around the same time.

Indeed fixed in the linked commit :+1:
