### ISSUE TITLE
[dev mode] Import Project - Upload fails

### ISSUE THREAD

**Issue by jerdna-regeiz** [orchest/orchest#1086]
In the current master you can't import a Project by uploading files.

When you go to Projects -> Import Project -> Drag & Drop a folder the request failes with a "werkzeug.exceptions.BadRequest".

```
Traceback (most recent call last):          
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode              
    obj, end = self.scan_once(s, idx)       
StopIteration: 0                            

During handling of the above exception, another exception occurred:                     

Traceback (most recent call last):          
  File "/usr/local/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 119, in get_json
    rv = self.json_module.loads(data)       
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 253, in loads
    return _json.loads(s, **kwargs)         
  File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads                  
    return cls(**kw).decode(s)              
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode                  
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                   
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode              
    raise JSONDecodeError("Expecting value", s, err.value) from None                    
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                 

During handling of the above exception, another exception occurred:                     

Traceback (most recent call last):          
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)     
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)              
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)              
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)        
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value                             
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()                                             
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)        
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)                                          
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2267, in process_response
    response = handler(response)            
  File "/orchest/services/orchest-webserver/app/app/__init__.py", line 207, in teardown
    pformat(request.get_json()),            
  File "/usr/local/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 128, in get_json
    rv = self.on_json_loading_failed(e)     
  File "/usr/local/lib/python3.8/site-packages/flask/wrappers.py", line 25, in on_json_loading_failed
    raise BadRequest("Failed to decode JSON object: {0}".format(e))                     
werkzeug.exceptions.BadRequest: 400 Bad Request: Failed to decode JSON object: Expecting value: line 1 column 1 (char 0)
```

This is caused by the logging which expects the request to be json, but in this case the data seems to be empty.

`File "/orchest/services/orchest-webserver/app/app/__init__.py", line 207, in teardown`:

```
            app.logger.debug(
                "%s %s %s\n[Request object]: %s",
                request.method,
                request.path,
                response.status,
                pformat(request.get_json()),
            )

```

If i catch the error, it works smoothly. But my knowledge is to limited and I can't decide if this is the root cause or if it would just shadow an other bug.

```
        try:
            app.logger.debug(
                "%s %s %s\n[Request object]: %s",
                request.method,
                request.path,
                response.status,
                pformat(request.get_json()),
            )
        except werkzeug.exceptions.BadRequest:
            app.logger.debug(
                "%s %s %s\n[Request object]: %s",
                request.method,
                request.path,
                response.status,
                request.data,
            )
```

**Comment by fruttasecca** [comment]
Hi @jerdna-regeiz , thanks for reporting the issue. We will be looking into it, probably today.

>In the current master you can't import a Project by uploading files

Just to be sure, are you in `--dev` mode?

**Comment by jerdna-regeiz** [comment]
> Just to be sure, are you in `--dev` mode?

Pretty sure, with working hot reload and settings page says `development mode`

**Comment by fruttasecca** [comment]
Alright sounds good, I think it will be an easy fix, the fix actually already exists in `services/auth-server/app/app/__init__.py`, `register_teardown_request`. I can make a PR for it later today and trigger a release or, if you prefer, you can propose a PR yourself, whatever works for you really.

**Comment by ricklamers** [comment]
Thanks for reporting this edge case @jerdna-regeiz :pray:

**Comment by jerdna-regeiz** [comment]
You're welcome, I'll do a quick PR! Keep up the awesome project!
