### ISSUE TITLE
Handle Jupyter notebook kernel writing more flexibly in pipeline save

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#264]
We are currently making to many assumptions about the structure of the JSON encoding of the Jupyter notebook when saving the pipeline file.

When the notebook file deviates from the expected format the save endpoint produces an error:

```
ERROR:app:app.py - [23/May/2021 12:30:59] - Exception on /async/pipelines/json/52d41e28-a23d-42da-90c8-ecea9068ed97/0915b350-b929-4cbd-b0d4-763cac0bb69f [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/orchest/services/orchest-webserver/app/app/views/views.py", line 703, in pipelines_json
    pipeline_set_notebook_kernels(
  File "/orchest/services/orchest-webserver/app/app/utils.py", line 678, in pipeline_set_notebook_kernels
    if notebook_json["metadata"]["kernelspec"]["language"] != language:
KeyError: 'language'
```

**To Reproduce**  
Save a notebook that doesn't contain the above metadata->kernelspec->language JSON structure.

**Comment by yannickperrenet** [comment]
We probably need to have a discussion here on how we plan to solve this issue.

Some notes while thinking about this:
* If a user changes the `metadata` then there is no way for us to figure out the `kernelspec` and we cannot be expected to do so. Similarly, if a user changes the `userdir` structure then Orchest breaks.
* Whenever this error happens we can write something like `undefined` to the `.pipeline` JSON file which the frontend can then handle when trying to do runs, display the step properties etc. Some sort of pipeline schema validator.

**Comment by ricklamers** [comment]
Just want to note here that the main goal is to not let Orchest break, not necessarily perfectly handle all edge cases (all kinds of Jupyter Notebook definitions).
