### ISSUE TITLE
Error Starting Kernel

### ISSUE THREAD

**Issue by jjdblast** [orchest/orchest#335]
**Describe the bug**  
Can not start jupyter lab kernel in pipeline, "Error attempting to connect to Gateway server url 'http://jupyter-EG-ebe7ef53-06d6-47d7-0915b350-b929-4cbd:8888'.  Ensure gateway url is valid and the Gateway instance is running." , docker logs shows that "Error loading kernelspec 'python3'"

**To Reproduce**  

1. Load pipeline from "https://github.com/orchest/quickstart"
2. Click on 'Pipeline' and run into one of notebooks
3. See error: "Error Starting Kernel: Error attempting to connect to Gateway server url 'http://jupyter-EG-ebe7ef53-06d6-47d7-0915b350-b929-4cbd:8888'.  Ensure gateway url is valid and the Gateway instance is running."

**Expected behavior**  
Start kernel normally.

**Screenshots**  
![image](https://user-images.githubusercontent.com/3394810/122852996-17796280-d344-11eb-979f-44dae7c077b7.png)

**Environment**

- OS: Ubuntu 20.04 LTS
- Browser: Chrome
- Version: v2021.06.3
- Environment: development on localhost
- Logs: [what do you see after running `./orchest status --ext`?]
  ```sh
  #./orchest status --ext
  Orchest is running.
  Performing extensive status checks...
  All services are ready.
  ```

  ```sh
  #./orchest version --ext
  Getting versions of all containers...
  orchest/jupyter-enterprise-gateway:latest   : v2021.06.3
  orchest/jupyter-server:latest               : v2021.06.3
  orchest/memory-server:latest                : v2021.06.3
  orchest/session-sidecar:latest              : v2021.06.3
  orchest/update-server:latest                : v2021.06.3
  orchest/orchest-api:latest                  : v2021.06.3
  orchest/orchest-webserver:latest            : v2021.06.3
  orchest/celery-worker:latest                : v2021.06.3
  orchest/auth-server:latest                  : v2021.06.3
  orchest/file-manager:latest                 : v2021.06.3
  orchest/nginx-proxy:latest                  : v2021.06.3
  orchest/base-kernel-py:latest               : v2021.06.3
  All containers are running on the same version of Orchest. Happy coding!
  ```

  ```sh
  # docker ps
  CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
  965a54ef1646        orchest/jupyter-server:latest        "/start.sh --allow-r…"   22 minutes ago      Up 22 minutes                                                             jupyter-server-ebe7ef53-06d6-47d7-0915b350-b929-4cbd
  9e2e934e0ff0        orchest/jupyter-enterprise-gateway   "tini -g -- /usr/loc…"   22 minutes ago      Up 22 minutes       8888/tcp                                              jupyter-EG-ebe7ef53-06d6-47d7-0915b350-b929-4cbd
  f9a329184b0c        orchest/session-sidecar:latest       "/bin/sh -c 'umask 0…"   22 minutes ago      Up 22 minutes                                                             session-sidecar-ebe7ef53-06d6-47d7-a70f-b4c1cb4425f6-0915b350-b929-4cbd-b0d4-763cac0bb69f
  24e9ac42029c        orchest/memory-server:latest         "python app/main.py"     22 minutes ago      Up 22 minutes                                                             memory-server-ebe7ef53-06d6-47d7-a70f-b4c1cb4425f6-0915b350-b929-4cbd-b0d4-763cac0bb69f
  7097d1e4c181        orchest/nginx-proxy:latest           "/usr/bin/openresty …"   About an hour ago   Up About an hour    0.0.0.0:8000->80/tcp                                  nginx-proxy
  901ab281f983        orchest/celery-worker:latest         "./../start_celery_w…"   About an hour ago   Up About an hour                                                          celery-worker
  819f379579d1        orchest/auth-server:latest           "/entrypoint.sh /sta…"   About an hour ago   Up About an hour    80/tcp                                                auth-server
  9ef67ca1c050        orchest/orchest-webserver:latest     "/entrypoint.sh /sta…"   About an hour ago   Up About an hour    80/tcp                                                orchest-webserver
  3c76bb1df2ec        orchest/orchest-api:latest           "/entrypoint.sh /sta…"   About an hour ago   Up About an hour    80/tcp                                                orchest-api
  5fa52936f179        postgres:13.1                        "docker-entrypoint.s…"   About an hour ago   Up About an hour    5432/tcp                                              orchest-database
  56f28dea5902        orchest/file-manager:latest          "/bin/sh -c 'umask 0…"   About an hour ago   Up About an hour    80/tcp                                                file-manager
  4d8c62be7c30        rabbitmq:3                           "docker-entrypoint.s…"   About an hour ago   Up About an hour    4369/tcp, 5671-5672/tcp, 15691-15692/tcp, 25672/tcp   rabbitmq-server
  ```

  ```sh
  # docker logs  jupyter-EG-ebe7ef53-06d6-47d7-0915b350-b929-4cbd
  Starting Jupyter Enterprise Gateway...
  [D 2021-06-22 02:10:30.958 EnterpriseGatewayApp] Searching ['/usr/local/bin', '/home/jovyan/.jupyter', '/opt/conda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
  [D 2021-06-22 02:10:30.958 EnterpriseGatewayApp] Looking for jupyter_config in /etc/jupyter
  [D 2021-06-22 02:10:30.958 EnterpriseGatewayApp] Looking for jupyter_config in /usr/local/etc/jupyter
  [D 2021-06-22 02:10:30.958 EnterpriseGatewayApp] Looking for jupyter_config in /opt/conda/etc/jupyter
  [D 2021-06-22 02:10:30.958 EnterpriseGatewayApp] Looking for jupyter_config in /home/jovyan/.jupyter
  [D 2021-06-22 02:10:30.958 EnterpriseGatewayApp] Looking for jupyter_config in /usr/local/bin
  [D 2021-06-22 02:10:30.959 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /etc/jupyter
  [D 2021-06-22 02:10:30.959 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /usr/local/etc/jupyter
  [D 2021-06-22 02:10:30.959 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /opt/conda/etc/jupyter
  [D 2021-06-22 02:10:30.959 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /home/jovyan/.jupyter
  [D 2021-06-22 02:10:30.959 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /usr/local/bin
  [D 210622 02:10:30 selector_events:58] Using selector: EpollSelector
  [I 2021-06-22 02:10:30.966 EnterpriseGatewayApp] Jupyter Enterprise Gateway 2.3.0 is available at http://0.0.0.0:8888
  [D 2021-06-22 02:10:37.768 EnterpriseGatewayApp] Found kernel python3 in /opt/conda/share/jupyter/kernels
  [D 2021-06-22 02:10:37.768 EnterpriseGatewayApp] Found kernel orchest-kernel-c56ab762-539c-4cce-9b1e-c4b00300ec6f in /usr/local/share/jupyter/kernels
  [W 2021-06-22 02:10:37.769 EnterpriseGatewayApp] Error loading kernelspec 'python3'
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 257, in get_all_specs
          spec = self._get_kernel_spec_by_name(kname, resource_dir)
        File "/opt/conda/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 200, in _get_kernel_spec_by_name
          return self.kernel_spec_class.from_resource_dir(resource_dir)
        File "/opt/conda/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 46, in from_resource_dir
          kernel_dict = json.load(f)
        File "/opt/conda/lib/python3.7/json/__init__.py", line 296, in load
          parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
        File "/opt/conda/lib/python3.7/json/__init__.py", line 348, in loads
          return _default_decoder.decode(s)
        File "/opt/conda/lib/python3.7/json/decoder.py", line 337, in decode
          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "/opt/conda/lib/python3.7/json/decoder.py", line 355, in raw_decode
          raise JSONDecodeError("Expecting value", s, err.value) from None
      json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  [I 210622 02:10:37 web:2250] 200 GET /api/kernelspecs (172.18.0.13) 234.14ms
  [I 210622 02:10:55 web:2250] 200 GET /api/kernels (172.18.0.13) 1.33ms
  ...
  [I 210622 02:12:40 web:2250] 200 GET /api/kernelspecs (172.18.0.13) 3.57ms
  [I 210622 02:14:05 web:2250] 200 GET /api/kernels (172.18.0.13) 1.13ms
  [D 2021-06-22 02:15:04.875 EnterpriseGatewayApp] RemoteMappingKernelManager.start_kernel: orchest-kernel-c56ab762-539c-4cce-9b1e-c4b00300ec6f, kernel_username: root
  [D 2021-06-22 02:15:04.886 EnterpriseGatewayApp] Instantiating kernel 'Python 3' with process proxy: enterprise_gateway.services.processproxies.docker_swarm.DockerProcessProxy
  [D 210622 02:15:04 config:21] Trying paths: ['/home/jovyan/.docker/config.json', '/home/jovyan/.dockercfg']
  [D 210622 02:15:04 config:28] No config file found
  [D 210622 02:15:04 config:21] Trying paths: ['/home/jovyan/.docker/config.json', '/home/jovyan/.dockercfg']
  [D 210622 02:15:04 config:28] No config file found
  [D 2021-06-22 02:15:04.946 EnterpriseGatewayApp] Response socket launched on '172.18.0.12:35833' using 5.0s timeout
  [D 2021-06-22 02:15:04.946 EnterpriseGatewayApp] Starting kernel (async): ['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/launch_docker.py', '--RemoteProcessProxy.kernel-id', '20fabae5-a088-4dfe-b37e-847b18db2c3e', '--RemoteProcessProxy.response-address', '172.18.0.12:35833']
  [D 2021-06-22 02:15:04.947 EnterpriseGatewayApp] Launching kernel: 'Python 3' with command: ['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/launch_docker.py', '--RemoteProcessProxy.kernel-id', '20fabae5-a088-4dfe-b37e-847b18db2c3e', '--RemoteProcessProxy.response-address', '172.18.0.12:35833']
  [D 2021-06-22 02:15:04.947 EnterpriseGatewayApp] BaseProcessProxy.launch_process() env: {'PATH': '/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'ORCHEST_HOST_PIPELINE_FILE': '/home/jiandong/orchest/orchest/userdir/projects/quickstart/california_housing.orchest', 'ORCHEST_PROJECT_UUID': 'ebe7ef53-06d6-47d7-a70f-b4c1cb4425f6', 'ORCHEST_PIPELINE_UUID': '0915b350-b929-4cbd-b0d4-763cac0bb69f', 'ORCHEST_HOST_PROJECT_DIR': '/home/jiandong/orchest/orchest/userdir/projects/quickstart', 'ORCHEST_HOST_GID': '1000', 'ORCHEST_SESSION_UUID': '0915b350-b929-4cbd-b0d4-763cac0bb69f', 'ORCHEST_PIPELINE_PATH': '/pipeline.json', 'ORCHEST_SESSION_TYPE': 'interactive', 'KERNEL_LAUNCH_TIMEOUT': '40', 'KERNEL_WORKING_DIR': '/project-dir', 'KERNEL_USERNAME': 'root', 'KERNEL_GATEWAY': '1', 'EG_DOCKER_NETWORK': 'orchest', 'EG_DOCKER_MODE': 'docker', 'KERNEL_IMAGE': 'orchest-env-ebe7ef53-06d6-47d7-a70f-b4c1cb4425f6-c56ab762-539c-4cce-9b1e-c4b00300ec6f', 'KERNEL_EXECUTOR_IMAGE': 'orchest-env-ebe7ef53-06d6-47d7-a70f-b4c1cb4425f6-c56ab762-539c-4cce-9b1e-c4b00300ec6f', 'KERNEL_UID': '1000', 'KERNEL_GID': '100', 'EG_MIN_PORT_RANGE_SIZE': '1000', 'EG_MAX_PORT_RANGE_RETRIES': '5', 'KERNEL_ID': '20fabae5-a088-4dfe-b37e-847b18db2c3e', 'KERNEL_LANGUAGE': 'python', 'EG_IMPERSONATION_ENABLED': 'False'}
  [I 2021-06-22 02:15:04.952 EnterpriseGatewayApp] DockerProcessProxy: kernel launched. Kernel image: orchest-env-ebe7ef53-06d6-47d7-a70f-b4c1cb4425f6-c56ab762-539c-4cce-9b1e-c4b00300ec6f, KernelID: 20fabae5-a088-4dfe-b37e-847b18db2c3e, cmd: '['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/launch_docker.py', '--RemoteProcessProxy.kernel-id', '20fabae5-a088-4dfe-b37e-847b18db2c3e', '--RemoteProcessProxy.response-address', '172.18.0.12:35833']'
  Started Jupyter kernel in normal docker mode
  Traceback (most recent call last):
    File "/usr/local/share/jupyter/kernels/launch_docker.py", line 148, in <module>
      launch_docker_kernel(kernel_id, response_addr, spark_context_init_mode)
    File "/usr/local/share/jupyter/kernels/launch_docker.py", line 109, in launch_docker_kernel
      image_name, volumes=orchest_mounts, device_requests=device_requests, **kwargs
    File "/opt/conda/lib/python3.7/site-packages/docker/models/containers.py", line 810, in run
      detach=detach, **kwargs)
    File "/opt/conda/lib/python3.7/site-packages/docker/models/containers.py", line 867, in create
      create_kwargs = _create_container_args(kwargs)
    File "/opt/conda/lib/python3.7/site-packages/docker/models/containers.py", line 1085, in _create_container_args
      create_kwargs['host_config'] = HostConfig(**host_config_kwargs)
    File "/opt/conda/lib/python3.7/site-packages/docker/types/containers.py", line 639, in __init__
      raise host_config_version_error('device_requests', '1.40')
  docker.errors.InvalidVersion: device_requests param is not supported in API versions < 1.40
  [D 2021-06-22 02:15:05.459 EnterpriseGatewayApp] 1: Waiting to connect to docker container. Name: '', Status: 'None', IPAddress: 'None', KernelID: '20fabae5-a088-4dfe-b37e-847b18db2c3e'
  [D 2021-06-22 02:15:05.459 EnterpriseGatewayApp] response socket still open, close it
  [E 2021-06-22 02:15:05.459 EnterpriseGatewayApp] Error occurred during launch of KernelID: 20fabae5-a088-4dfe-b37e-847b18db2c3e.  Check Enterprise Gateway log for more information.
 
  ```

**Comment by yannickperrenet** [comment]
Thanks for raising this issue. So far I was unable to reproduce this issue. I noticed you raised another issue (#329) which indicates that you were running on an (considerably) older version of Orchest. Could you try whether runing the `scripts/clean_userdir.sh` script fixes your issue? **Please note** that this will remove all Orchest state and files in your `userdir`, if this is a problem for you then please let me know.

Regarding the `JSONDecodeError` you see in the logs, this is actually done on purpose (see #297).

**Comment by ricklamers** [comment]
Hi @jjdblast.

It looks like you have an older version of Docker installed on your system. The Docker API seems to be below 1.40 as per this error:

> docker.errors.InvalidVersion: device_requests param is not supported in API versions < 1.40

Could you make sure you're on the latest Docker version?

**Comment by jjdblast** [comment]
@ricklamers @yannickperrenet It seems like my docker version was also too old, after I updated my docker version to 20.10.7 ( API version: 1.41), everything works like a charm. Thanks !

**Comment by ricklamers** [comment]
Great to hear it’s working. Moving forward we’ll mention the minimum Docker version we tested against in the system requirements.
