### ISSUE TITLE
`orchest-webserver` chokes regularly in development

### ISSUE THREAD

**Issue by joe-bell** [orchest/orchest#389]
**Describe the bug**  

When running `orchest start --dev` and `pnpm run dev` – if many file changes are made or too many requests hit `localhost:8000` in a short period of time, the page will appear as a white screen and stuck in a "loading" state.

Given that `localhost:3000` is still functioning (the original vite server path, re-routed by NGINX), I believe this is **not** Vite related.

This behaviour is also common during the development of #384 when running `pnpm run cy:open` – where many "visits" are triggered to `localhost:8000` in quick succession. 

<details>
   <summary><strong>View <code>orchest-webserver</code> Docker Logs</strong></summary>

  ```
  INFO:socketio.client:Engine.IO connection dropped
  INFO:socketio.client:Connection failed, new attempt in 1.13 seconds
  INFO:socketio.client:Connection failed, new attempt in 1.90 seconds
  INFO:socketio.client:Connection failed, new attempt in 3.63 seconds
  INFO:socketio.client:Connection failed, new attempt in 4.62 seconds
  INFO:socketio.client:Connection failed, new attempt in 5.30 seconds
  INFO:socketio.client:Connection failed, new attempt in 4.98 seconds
  INFO:socketio.client:Connection failed, new attempt in 5.42 seconds
  INFO:socketio.client:Connection failed, new attempt in 5.41 seconds
  INFO:socketio.client:Connection failed, new attempt in 4.67 seconds
  INFO:socketio.client:Connection failed, new attempt in 4.64 seconds
  INFO:socketio.client:Connection failed, new attempt in 4.72 seconds
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
      conn = connection.create_connection(
    File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
      raise err
    File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
      sock.connect(sa)
  TimeoutError: [Errno 110] Connection timed out
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
      httplib_response = self._make_request(
    File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
      conn.request(method, url, **httplib_request_kw)
    File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
      super(HTTPConnection, self).request(method, url, body=body, headers=headers)
    File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
      self.send(msg)
    File "/usr/local/lib/python3.8/http/client.py", line 950, in send
      self.connect()
    File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
      conn = self._new_conn()
    File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
      raise NewConnectionError(
  urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f00e5681ca0>: Failed to establish a new connection: [Errno 110] Connection timed out
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
      resp = conn.urlopen(
    File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
      retries = retries.increment(
    File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))
  urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=3000): Max retries exceeded with url: /src/components/ProjectFilePicker.tsx (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f00e5681ca0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
      response = self.handle_exception(e)
    File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
      return original_handler(e)
    File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
      return original_handler(e)
    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
      reraise(exc_type, exc_value, tb)
    File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
      raise value
    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
      response = self.full_dispatch_request()
    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
      rv = self.handle_user_exception(e)
    File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
      return original_handler(e)
    File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
      return original_handler(e)
    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
      reraise(exc_type, exc_value, tb)
    File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
      raise value
    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
      rv = self.dispatch_request()
    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
      return self.view_functions[rule.endpoint](**req.view_args)
    File "/orchest/services/orchest-webserver/app/app/__init__.py", line 165, in index
      return _proxy(request, app.config["CLIENT_DEV_SERVER_URL"] + "/")
    File "/orchest/lib/python/orchest-internals/_orchest/internals/utils.py", line 53, in _proxy
      resp = requests.request(
    File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
      return session.request(method=method, url=url, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
      resp = self.send(prep, **send_kwargs)
    File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
      r = adapter.send(request, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
      raise ConnectionError(e, request=request)
  requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=3000): Max retries exceeded with url: /src/components/ProjectFilePicker.tsx (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f00e5681ca0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 172.18.0.10 - - [15/Jul/2021 11:02:01] "GET /src/components/ProjectFilePicker.tsx HTTP/1.1" 500 61623 131.491761
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=polling&EIO=3&t=1626346822.8752632 HTTP/1.1" 200 371 0.000311
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 172.18.0.10 - - [15/Jul/2021 11:02:01] "GET /src/components/Layout/OnboardingDialog/use-onboarding-dialog.ts HTTP/1.1" 304 150 0.004937
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 172.18.0.10 - - [15/Jul/2021 11:02:01] "GET /src/components/Layout/OnboardingDialog/OnboardingDialog.tsx HTTP/1.1" 304 150 0.004978
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 172.18.0.10 - - [15/Jul/2021 11:02:01] "GET /src/icons/index.tsx HTTP/1.1" 304 150 0.005467
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 172.18.0.10 - - [15/Jul/2021 11:02:01] "GET /catch/api-proxy/api/sessions/ HTTP/1.1" 200 662 0.006888
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=polling&EIO=3&t=1626346829.7826877 HTTP/1.1" 200 371 0.000444
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=polling&EIO=3&t=1626346838.422442 HTTP/1.1" 200 371 0.000379
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=polling&EIO=3&t=1626346848.0157368 HTTP/1.1" 200 371 0.000323
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=polling&EIO=3&t=1626346858.33087 HTTP/1.1" 200 371 0.000269
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=polling&EIO=3&t=1626346868.3244529 HTTP/1.1" 200 371 0.000301
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=polling&EIO=3&t=1626346878.7158773 HTTP/1.1" 200 371 0.000262
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=polling&EIO=3&t=1626346889.1393743 HTTP/1.1" 200 371 0.000263
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=polling&EIO=3&t=1626346898.8111377 HTTP/1.1" 200 371 0.000224
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=polling&EIO=3&t=1626346908.4265947 HTTP/1.1" 200 371 0.000272
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=polling&EIO=3&t=1626346918.1544318 HTTP/1.1" 200 371 0.000427
  INFO:app:wsgi.py - [15/Jul/2021 11:02:01] - 127.0.0.1 - - [15/Jul/2021 11:02:01] "GET /socket.io/?transport=websocket&EIO=3&sid=41b5811f4f70410782f2908838326c8d&t=1626345496.6941328 HTTP/1.1" 200 0 1424.472881
  INFO:socketio.client:Engine.IO connection established
  INFO:socketio.client:Namespace / is connected
  INFO:app:socketio_server.py - [15/Jul/2021 11:02:01] - socket.io client connected on /pty
  INFO:socketio.client:Reconnection successful
  INFO:socketio.client:Namespace /pty is connected
  INFO:root:SocketIO connection established on namespace /pty
  ```

</details>

**To Reproduce**  

1. Run `orchest start --dev` and `pnpm run dev` in parallel (and/or with #384's `pnpm run cy:open`)
2. Make many changes
3. Try multiple refresh
4. See crash

**Expected behavior**  

Given that it's expected to be running tests in development (and in fact encouraged by Cypress), our development server must be able to support more requests than it currently does

Even better – a single script rather than running `orchest start --dev` and `pnpm run dev` in parallel

**Additional context**

**Comment by yannickperrenet** [comment]
Some work has been done in #399.

**Comment by fruttasecca** [comment]
The issue **seems** to be related to an interaction between websockets and vite.
For testing purposes you can use this `curl` snippet to make the dev mode client hang.
```bash
curl --include \                                                                                                                                        
     --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: localhost:8000" \
     --header "Origin: http://localhost:80" \
          --header "Sec-WebSocket-Version: 13" \         
     http://localhost:8000
```
See this [branch](https://github.com/orchest/orchest/commits/fix/socketio-dev-server) for a WIP solution.
