### ISSUE TITLE
Stuck in Getting ready to build...

### ISSUE THREAD

**Issue by ZhaoHuiXin** [orchest/orchest#995]
build enviroment stuck in Getting ready to build...

when i get logs use below command
`kubectl logs -n orchest -f deployment/orchest-api`

it show me these:
(Background on this error at: https://sqlalche.me/e/14/e3q8)
INFO:job-scheduler:scheduler.py - [27/May/2022 02:06:58] - SchedulerJob running process_notification_deliveries: PID 11.
WARNING:celery.backends.database:__init__.py - [27/May/2022 02:07:04] - Failed operation _forget.  Retrying 2 more times.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3256, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/usr/local/lib/python3.8/site-packages/eventlet/support/psycopg2_patcher.py", line 46, in eventlet_wait_callback
    state = conn.poll()
psycopg2.OperationalError: FATAL:  database "celery_result_backend" does not exist

**Environment**
- OS (e.g. macOS):
- Browser (e.g. Chrome):
- Orchest's version (in the settings page):

OS: MACOS
Browser: Chrome
Orchest Version: v2022.05.3

**Comment by ZhaoHuiXin** [comment]
all my pods under namespace orchest is Running 
![image](https://user-images.githubusercontent.com/32922054/170625930-80e59e0f-bc61-4b4b-b9be-c9ab799cac6c.png)

**Comment by astrojuanlu** [comment]
Hi @ZhaoHuiXin , I'm sorry you had a bumpy start - did you close the issue because you solved the problem? Would you like to elaborate a bit more?

**Comment by ZhaoHuiXin** [comment]
@astrojuanlu  #991 I followed this advice, restart orchest and it worked

**Comment by astrojuanlu** [comment]
Awesome, thanks for following up!
